{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ww.tools",
    "module": "uichecker",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uichecker-1.0.0.aar",
          "url": "uichecker-1.0.0.aar",
          "size": 96933,
          "sha512": "7d30ddee5f8bdb94455c3e1f702f327672df1844477bb30d9b904f992b00403ab0c574e56c9e81d3eb3958a891cc94c4ddae18ab218ea49bf7bfcb1d8f89fda2",
          "sha256": "f8eda93bb1363499a7311cc7cad60b07ba271123134fae12ec35d72f7a46be7f",
          "sha1": "e4575c4df41426fc0a0677efc44e067367d22765",
          "md5": "a15e12e0f45eda63844806287d27b0a8"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uichecker-1.0.0.aar",
          "url": "uichecker-1.0.0.aar",
          "size": 96933,
          "sha512": "7d30ddee5f8bdb94455c3e1f702f327672df1844477bb30d9b904f992b00403ab0c574e56c9e81d3eb3958a891cc94c4ddae18ab218ea49bf7bfcb1d8f89fda2",
          "sha256": "f8eda93bb1363499a7311cc7cad60b07ba271123134fae12ec35d72f7a46be7f",
          "sha1": "e4575c4df41426fc0a0677efc44e067367d22765",
          "md5": "a15e12e0f45eda63844806287d27b0a8"
        }
      ]
    }
  ]
}
