{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ww.tools",
    "module": "uichecker",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uichecker-1.0.0.aar",
          "url": "uichecker-1.0.0.aar",
          "size": 123948,
          "sha512": "6f3efbb5b4ac561713f1a9ec83edc1b7dd4a99786ec304240b91efa18dd4b3f569d0bd686563b06b4d9805eebc6ad4d25b2e1b0c632dab34c90ddfb481fb9bb4",
          "sha256": "e13ba4262c0035f8e1260c9c12685473ba6c3e817a9ee7698b50701ca60522fb",
          "sha1": "2f05fbe059f118175f413236b22265d2aa6474f7",
          "md5": "af6dcdc9adefd6633372d5c19a769dac"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "uichecker-1.0.0.aar",
          "url": "uichecker-1.0.0.aar",
          "size": 123948,
          "sha512": "6f3efbb5b4ac561713f1a9ec83edc1b7dd4a99786ec304240b91efa18dd4b3f569d0bd686563b06b4d9805eebc6ad4d25b2e1b0c632dab34c90ddfb481fb9bb4",
          "sha256": "e13ba4262c0035f8e1260c9c12685473ba6c3e817a9ee7698b50701ca60522fb",
          "sha1": "2f05fbe059f118175f413236b22265d2aa6474f7",
          "md5": "af6dcdc9adefd6633372d5c19a769dac"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "uichecker-1.0.0-sources.jar",
          "url": "uichecker-1.0.0-sources.jar",
          "size": 69041,
          "sha512": "60a18fd93d124128d9a5dffa32265bf35af3d7947cd4c8e15c9fc2cd328909f49df3a707eceacd5d982dc1c53b9dbc1ee637a28ee6f9f11bb333dafc5b1fbcde",
          "sha256": "97850c42ffde29974bf7cb82f8b281195b58d6897344b4edd664083d6729961d",
          "sha1": "28385c64d115fc8f6b04be23d64aabaea0224173",
          "md5": "8ba95a69cde6b09c2b11d54215e58b51"
        }
      ]
    }
  ]
}
